<?php

namespace Database\Seeders;

use App\Models\Contract;
use App\Models\ContractIncident;
use App\Models\ContractStatusHistory;
use App\Models\Tenant;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Collection;

class ContractSeeder extends Seeder
{
    public function run(): void
    {
        // Get all active tenants (expect 5 from DatabaseSeeder)
        $tenants = Tenant::where('status', 'active')->get();
        if ($tenants->isEmpty()) {
            return;
        }

        // Get first tenant for finding users
        $firstTenant = $tenants->first();

        $manager = User::where('tenant_id', $firstTenant->id)
            ->whereHas('roles', fn ($q) => $q->where('name', 'Manager'))
            ->first();

        $technician = User::where('tenant_id', $firstTenant->id)
            ->whereHas('roles', fn ($q) => $q->where('name', 'Technician'))
            ->first();

        $viewer = User::where('tenant_id', $firstTenant->id)
            ->whereHas('roles', fn ($q) => $q->where('name', 'Viewer'))
            ->first();

        $fallbackUsers = User::where('tenant_id', $firstTenant->id)->take(3)->get();
        if ($fallbackUsers->count() < 3) {
            return;
        }

        // index 0 = client-ish user, 1 = assignee, 2 = alternate assignee/client
        $users = collect([
            $manager ?? $fallbackUsers[0],
            $technician ?? $fallbackUsers[1],
            $viewer ?? $fallbackUsers[2],
        ])->values();

        $now = now();

        $contracts = [
            // IN_PROGRESS (existing)
            [
                'contract_number' => 'CT-2026-001',
                'title' => 'Downtown Office HVAC Maintenance',
                'description' => 'Quarterly HVAC system maintenance and inspection for downtown office building.',
                'client_id' => $users[0]->id,
                'assigned_to' => $users[1]->id,
                'status' => 'in_progress',
                'priority' => 'high',
                'start_date' => $now->copy()->subMonths(2),
                'due_date' => $now->copy()->addMonths(10),
                'budget' => 45000.00,
                'spent' => 12500.00,
                'sla_hours' => 96,
            ],
            [
                'contract_number' => 'CT-2026-002',
                'title' => 'Industrial Plant Network Upgrade',
                'description' => 'Complete network infrastructure upgrade and monitoring system installation.',
                'client_id' => $users[0]->id,
                'assigned_to' => $users[2]->id,
                'status' => 'in_progress',
                'priority' => 'high',
                'start_date' => $now->copy()->subMonths(1),
                'due_date' => $now->copy()->addMonths(5),
                'budget' => 125000.00,
                'spent' => 55000.00,
                'sla_hours' => 48,
            ],
            [
                'contract_number' => 'CT-2026-003',
                'title' => 'Hospital Facility Management',
                'description' => 'Comprehensive facility management including preventive maintenance and emergency response.',
                'client_id' => $users[1]->id,
                'assigned_to' => $users[2]->id,
                'status' => 'in_progress',
                'priority' => 'critical',
                'start_date' => $now->copy()->subMonths(3),
                'due_date' => $now->copy()->addMonths(21),
                'budget' => 250000.00,
                'spent' => 87500.00,
                'sla_hours' => 24,
            ],
            [
                'contract_number' => 'CT-2026-008',
                'title' => 'Warehouse IoT Sensor Grid',
                'description' => 'Sensor rollout for humidity and temperature monitoring in cold storage lanes.',
                'client_id' => $users[2]->id,
                'assigned_to' => $users[0]->id,
                'status' => 'in_progress',
                'priority' => 'high',
                'start_date' => $now->copy()->subMonths(1),
                'due_date' => $now->copy()->addMonths(2),
                'budget' => 73000.00,
                'spent' => 52500.00,
                'sla_hours' => 36,
            ],
            [
                'contract_number' => 'CT-2026-018',
                'title' => 'Smart Building Control System',
                'description' => 'IoT-based building automation across 3 locations.',
                'client_id' => $users[1]->id,
                'assigned_to' => $users[2]->id,
                'status' => 'in_progress',
                'priority' => 'medium',
                'start_date' => $now->copy()->subWeeks(4),
                'due_date' => $now->copy()->addMonths(3),
                'budget' => 95000.00,
                'spent' => 31500.00,
                'sla_hours' => 72,
            ],
            [
                'contract_number' => 'CT-2026-021',
                'title' => 'Corporate Office Renovation',
                'description' => 'Complete office space renovation with modern workspace setup.',
                'client_id' => $users[0]->id,
                'assigned_to' => $users[1]->id,
                'status' => 'in_progress',
                'priority' => 'high',
                'start_date' => $now->copy()->subWeeks(6),
                'due_date' => $now->copy()->addMonths(2),
                'budget' => 180000.00,
                'spent' => 95000.00,
                'sla_hours' => 60,
            ],
            [
                'contract_number' => 'CT-2026-022',
                'title' => 'Data Center Cooling System',
                'description' => 'Installation of redundant cooling system for data center.',
                'client_id' => $users[1]->id,
                'assigned_to' => $users[2]->id,
                'status' => 'in_progress',
                'priority' => 'critical',
                'start_date' => $now->copy()->subWeeks(2),
                'due_date' => $now->copy()->addMonths(1),
                'budget' => 340000.00,
                'spent' => 120000.00,
                'sla_hours' => 24,
            ],
            [
                'contract_number' => 'CT-2026-023',
                'title' => 'Retail Chain Security Upgrade',
                'description' => 'Security camera and alarm system upgrade across 12 locations.',
                'client_id' => $users[2]->id,
                'assigned_to' => $users[0]->id,
                'status' => 'in_progress',
                'priority' => 'medium',
                'start_date' => $now->copy()->subWeeks(8),
                'due_date' => $now->copy()->addWeeks(4),
                'budget' => 220000.00,
                'spent' => 150000.00,
                'sla_hours' => 48,
            ],
            [
                'contract_number' => 'CT-2026-030',
                'title' => 'Server Room Climate Control',
                'description' => 'Emergency temperature control system installation. High urgency.',
                'client_id' => $users[1]->id,
                'assigned_to' => $users[2]->id,
                'status' => 'in_progress',
                'priority' => 'critical',
                'start_date' => $now->copy()->subDays(3),
                'due_date' => $now->copy()->addHours(12),
                'budget' => 165000.00,
                'spent' => 42000.00,
                'sla_hours' => 12,
            ],

            // APPROVED (existing)
            [
                'contract_number' => 'CT-2026-004',
                'title' => 'Retail Chain Climate Control',
                'description' => 'HVAC and climate control maintenance for 15 retail locations.',
                'client_id' => $users[1]->id,
                'assigned_to' => null,
                'status' => 'approved',
                'priority' => 'medium',
                'start_date' => $now->copy()->addMonths(1),
                'due_date' => $now->copy()->addMonths(13),
                'budget' => 85000.00,
                'spent' => 0.00,
                'sla_hours' => 144,
            ],
            [
                'contract_number' => 'CT-2026-009',
                'title' => 'Municipal Building BMS Upgrade',
                'description' => 'Upgrade building management system and remote monitoring integrations.',
                'client_id' => $users[0]->id,
                'assigned_to' => $users[1]->id,
                'status' => 'approved',
                'priority' => 'medium',
                'start_date' => $now->copy()->addDays(7),
                'due_date' => $now->copy()->addDays(30),
                'budget' => 110000.00,
                'spent' => 0.00,
                'sla_hours' => 60,
            ],
            [
                'contract_number' => 'CT-2026-011',
                'title' => 'School District Parking Lot Lighting',
                'description' => 'LED lighting upgrade for 8 school parking facilities.',
                'client_id' => $users[0]->id,
                'assigned_to' => null,
                'status' => 'approved',
                'priority' => 'medium',
                'start_date' => $now->copy()->addMonths(1),
                'due_date' => $now->copy()->addMonths(4),
                'budget' => 65000.00,
                'spent' => 0.00,
                'sla_hours' => 96,
            ],
            [
                'contract_number' => 'CT-2026-014',
                'title' => 'Tech Campus Network Expansion',
                'description' => 'WiFi 6 network rollout across 4 buildings.',
                'client_id' => $users[2]->id,
                'assigned_to' => null,
                'status' => 'approved',
                'priority' => 'high',
                'start_date' => $now->copy()->addWeeks(2),
                'due_date' => $now->copy()->addMonths(2),
                'budget' => 145000.00,
                'spent' => 0.00,
                'sla_hours' => 48,
            ],
            [
                'contract_number' => 'CT-2026-017',
                'title' => 'Hospital Emergency Generator Service',
                'description' => 'Annual maintenance and testing of 3 emergency generators.',
                'client_id' => $users[1]->id,
                'assigned_to' => null,
                'status' => 'approved',
                'priority' => 'critical',
                'start_date' => $now->copy()->addMonths(1),
                'due_date' => $now->copy()->addMonths(2),
                'budget' => 55000.00,
                'spent' => 0.00,
                'sla_hours' => 12,
            ],
            [
                'contract_number' => 'CT-2026-024',
                'title' => 'Telecommunications Infrastructure',
                'description' => 'Fiber optic backbone installation in downtown area.',
                'client_id' => $users[1]->id,
                'assigned_to' => $users[2]->id,
                'status' => 'approved',
                'priority' => 'high',
                'start_date' => $now->copy()->addWeeks(2),
                'due_date' => $now->copy()->addMonths(5),
                'budget' => 580000.00,
                'spent' => 0.00,
                'sla_hours' => 72,
            ],
            [
                'contract_number' => 'CT-2026-025',
                'title' => 'Hospital Emergency Backup Power',
                'description' => 'Generator and battery backup system for critical hospital operations.',
                'client_id' => $users[0]->id,
                'assigned_to' => $users[1]->id,
                'status' => 'approved',
                'priority' => 'critical',
                'start_date' => $now->copy()->addMonths(1),
                'due_date' => $now->copy()->addMonths(4),
                'budget' => 450000.00,
                'spent' => 0.00,
                'sla_hours' => 36,
            ],
            [
                'contract_number' => 'CT-2026-026',
                'title' => 'Software License Maintenance',
                'description' => 'Annual software license renewal and support contract.',
                'client_id' => $users[2]->id,
                'assigned_to' => $users[0]->id,
                'status' => 'approved',
                'priority' => 'medium',
                'start_date' => $now->copy()->addMonths(2),
                'due_date' => $now->copy()->addMonths(14),
                'budget' => 95000.00,
                'spent' => 0.00,
                'sla_hours' => 96,
            ],

            // DONE (existing)
            [
                'contract_number' => 'CT-2026-005',
                'title' => 'Data Center Cooling Systems',
                'description' => '24/7 monitoring and maintenance of advanced data center cooling infrastructure.',
                'client_id' => $users[2]->id,
                'assigned_to' => $users[0]->id,
                'status' => 'done',
                'priority' => 'critical',
                'start_date' => $now->copy()->subMonths(12),
                'due_date' => $now->copy()->subDays(5),
                'budget' => 180000.00,
                'spent' => 180000.00,
                'completed_at' => $now->copy()->subDays(5),
                'sla_hours' => 12,
            ],
            [
                'contract_number' => 'CT-2026-010',
                'title' => 'Office Building Security Door Locks',
                'description' => 'Electronic lock installation and integration with access control system.',
                'client_id' => $users[0]->id,
                'assigned_to' => $users[1]->id,
                'status' => 'done',
                'priority' => 'high',
                'start_date' => $now->copy()->subMonths(2),
                'due_date' => $now->copy()->subDays(15),
                'budget' => 32000.00,
                'spent' => 32000.00,
                'completed_at' => $now->copy()->subDays(15),
                'sla_hours' => 72,
            ],
            [
                'contract_number' => 'CT-2026-012',
                'title' => 'Stadium Concourse Renovation',
                'description' => 'HVAC system modernization in concourse areas.',
                'client_id' => $users[1]->id,
                'assigned_to' => $users[2]->id,
                'status' => 'done',
                'priority' => 'high',
                'start_date' => $now->copy()->subMonths(3),
                'due_date' => $now->copy()->subDays(30),
                'budget' => 198000.00,
                'spent' => 198000.00,
                'completed_at' => $now->copy()->subDays(30),
                'sla_hours' => 48,
            ],
            [
                'contract_number' => 'CT-2026-013',
                'title' => 'Plant Automation Testing',
                'description' => 'Full system testing and validation.',
                'client_id' => $users[0]->id,
                'assigned_to' => $users[2]->id,
                'status' => 'done',
                'priority' => 'medium',
                'start_date' => $now->copy()->subMonths(2),
                'due_date' => $now->copy()->subDays(10),
                'budget' => 42000.00,
                'spent' => 42000.00,
                'completed_at' => $now->copy()->subDays(10),
                'sla_hours' => 96,
            ],
            [
                'contract_number' => 'CT-2026-015',
                'title' => 'Warehouse Inventory System',
                'description' => 'RFID-based inventory management system installation.',
                'client_id' => $users[2]->id,
                'assigned_to' => $users[0]->id,
                'status' => 'done',
                'priority' => 'high',
                'start_date' => $now->copy()->subMonths(3),
                'due_date' => $now->copy()->subDays(45),
                'budget' => 87500.00,
                'spent' => 87500.00,
                'completed_at' => $now->copy()->subDays(45),
                'sla_hours' => 60,
            ],
            [
                'contract_number' => 'CT-2026-016',
                'title' => 'Corporate Office Upgrade',
                'description' => 'Electrical system upgrade and testing.',
                'client_id' => $users[1]->id,
                'assigned_to' => $users[1]->id,
                'status' => 'done',
                'priority' => 'medium',
                'start_date' => $now->copy()->subMonths(4),
                'due_date' => $now->copy()->subMonths(2),
                'budget' => 76000.00,
                'spent' => 76000.00,
                'completed_at' => $now->copy()->subMonths(2),
                'sla_hours' => 120,
            ],
            [
                'contract_number' => 'CT-2026-019',
                'title' => 'Medical Clinic Infrastructure',
                'description' => 'Basic electrical and plumbing infrastructure.',
                'client_id' => $users[0]->id,
                'assigned_to' => $users[2]->id,
                'status' => 'done',
                'priority' => 'medium',
                'start_date' => $now->copy()->subMonths(3),
                'due_date' => $now->copy()->subMonths(1),
                'budget' => 58000.00,
                'spent' => 58000.00,
                'completed_at' => $now->copy()->subMonths(1),
                'sla_hours' => 84,
            ],
            [
                'contract_number' => 'CT-2026-028',
                'title' => 'Office Network Upgrade Completed',
                'description' => 'Network infrastructure upgrade completed on schedule.',
                'client_id' => $users[0]->id,
                'assigned_to' => $users[2]->id,
                'status' => 'done',
                'priority' => 'medium',
                'start_date' => $now->copy()->subMonths(4),
                'due_date' => $now->copy()->subMonths(1),
                'budget' => 125000.00,
                'spent' => 124500.00,
                'completed_at' => $now->copy()->subMonths(1),
                'sla_hours' => 60,
            ],
            [
                'contract_number' => 'CT-2026-029',
                'title' => 'Parking Lot LED Lighting',
                'description' => 'Parking lot lighting retrofit with LED and motion sensors.',
                'client_id' => $users[2]->id,
                'assigned_to' => $users[1]->id,
                'status' => 'done',
                'priority' => 'low',
                'start_date' => $now->copy()->subMonths(3),
                'due_date' => $now->copy()->subWeeks(2),
                'budget' => 85000.00,
                'spent' => 83000.00,
                'completed_at' => $now->copy()->subWeeks(2),
                'sla_hours' => 96,
            ],

            // BLOCKED (existing)
            [
                'contract_number' => 'CT-2026-006',
                'title' => 'Airport Security Camera Expansion',
                'description' => 'Waiting for final customer sign-off.',
                'client_id' => $users[0]->id,
                'assigned_to' => null,
                'status' => 'blocked',
                'priority' => 'medium',
                'start_date' => $now->copy()->subWeeks(2),
                'due_date' => $now->copy()->addMonths(4),
                'budget' => 92000.00,
                'spent' => 18500.00,
                'sla_hours' => 72,
            ],
            [
                'contract_number' => 'CT-2026-007',
                'title' => 'Factory Access Control Retrofit',
                'description' => 'Paused due to missing hardware shipment.',
                'client_id' => $users[1]->id,
                'assigned_to' => $users[2]->id,
                'status' => 'blocked',
                'priority' => 'high',
                'start_date' => $now->copy()->subWeeks(3),
                'due_date' => $now->copy()->addWeeks(4),
                'budget' => 64000.00,
                'spent' => 18000.00,
                'sla_hours' => 48,
            ],
            [
                'contract_number' => 'CT-2026-020',
                'title' => 'Port Authority Renovation Phase 2',
                'description' => 'Awaiting funding approval for phase 2.',
                'client_id' => $users[2]->id,
                'assigned_to' => null,
                'status' => 'blocked',
                'priority' => 'low',
                'start_date' => $now->copy()->subMonths(2),
                'due_date' => $now->copy()->addMonths(6),
                'budget' => 420000.00,
                'spent' => 89000.00,
                'sla_hours' => 144,
            ],
            [
                'contract_number' => 'CT-2026-027',
                'title' => 'Traffic Management System',
                'description' => 'Blocked awaiting city permits.',
                'client_id' => $users[1]->id,
                'assigned_to' => null,
                'status' => 'blocked',
                'priority' => 'high',
                'start_date' => $now->copy()->subMonths(1),
                'due_date' => $now->copy()->addMonths(3),
                'budget' => 350000.00,
                'spent' => 25000.00,
                'sla_hours' => 72,
            ],

            // ADDITIONS to reach ~15 per status

            // IN_PROGRESS +6
            [
                'contract_number' => 'CT-2026-031',
                'title' => 'Airport Terminal WiFi Stabilization',
                'description' => 'Stabilization works for public and operations wireless network.',
                'client_id' => $users[0]->id,
                'assigned_to' => $users[2]->id,
                'status' => 'in_progress',
                'priority' => 'high',
                'start_date' => $now->copy()->subWeeks(5),
                'due_date' => $now->copy()->addWeeks(6),
                'budget' => 132000.00,
                'spent' => 61000.00,
                'sla_hours' => 48,
            ],
            [
                'contract_number' => 'CT-2026-032',
                'title' => 'Hospital BMS Alarm Rationalization',
                'description' => 'Reduction of false alarms and routing to on-call groups.',
                'client_id' => $users[1]->id,
                'assigned_to' => $users[0]->id,
                'status' => 'in_progress',
                'priority' => 'critical',
                'start_date' => $now->copy()->subDays(20),
                'due_date' => $now->copy()->addDays(21),
                'budget' => 210000.00,
                'spent' => 98000.00,
                'sla_hours' => 24,
            ],
            [
                'contract_number' => 'CT-2026-033',
                'title' => 'Municipal CCTV Analytics Rollout',
                'description' => 'Deployment of AI-enabled analytics for traffic cameras.',
                'client_id' => $users[2]->id,
                'assigned_to' => $users[1]->id,
                'status' => 'in_progress',
                'priority' => 'medium',
                'start_date' => $now->copy()->subWeeks(7),
                'due_date' => $now->copy()->addWeeks(9),
                'budget' => 275000.00,
                'spent' => 112000.00,
                'sla_hours' => 72,
            ],
            [
                'contract_number' => 'CT-2026-034',
                'title' => 'Warehouse Fire Panel Replacement',
                'description' => 'Replacement of obsolete fire alarm control panel.',
                'client_id' => $users[0]->id,
                'assigned_to' => $users[1]->id,
                'status' => 'in_progress',
                'priority' => 'high',
                'start_date' => $now->copy()->subWeeks(3),
                'due_date' => $now->copy()->addWeeks(5),
                'budget' => 98000.00,
                'spent' => 47000.00,
                'sla_hours' => 36,
            ],
            [
                'contract_number' => 'CT-2026-035',
                'title' => 'Clinic UPS Fleet Renewal',
                'description' => 'UPS replacement across 14 outpatient facilities.',
                'client_id' => $users[1]->id,
                'assigned_to' => $users[2]->id,
                'status' => 'in_progress',
                'priority' => 'medium',
                'start_date' => $now->copy()->subWeeks(6),
                'due_date' => $now->copy()->addMonths(2),
                'budget' => 165000.00,
                'spent' => 85000.00,
                'sla_hours' => 60,
            ],
            [
                'contract_number' => 'CT-2026-036',
                'title' => 'Datacenter Cold-Aisle Containment',
                'description' => 'Build and tune cold-aisle containment for Hall C.',
                'client_id' => $users[2]->id,
                'assigned_to' => $users[0]->id,
                'status' => 'in_progress',
                'priority' => 'critical',
                'start_date' => $now->copy()->subDays(12),
                'due_date' => $now->copy()->addDays(18),
                'budget' => 305000.00,
                'spent' => 146000.00,
                'sla_hours' => 24,
            ],

            // APPROVED +7
            [
                'contract_number' => 'CT-2026-037',
                'title' => 'District Heating Controls Refresh',
                'description' => 'Controller replacement in 9 heating substations.',
                'client_id' => $users[0]->id,
                'assigned_to' => null,
                'status' => 'approved',
                'priority' => 'medium',
                'start_date' => $now->copy()->addWeeks(3),
                'due_date' => $now->copy()->addMonths(5),
                'budget' => 158000.00,
                'spent' => 0.00,
                'sla_hours' => 72,
            ],
            [
                'contract_number' => 'CT-2026-038',
                'title' => 'Police HQ Access Segmentation',
                'description' => 'Badge-access zoning and visitor route isolation.',
                'client_id' => $users[1]->id,
                'assigned_to' => $users[2]->id,
                'status' => 'approved',
                'priority' => 'high',
                'start_date' => $now->copy()->addDays(14),
                'due_date' => $now->copy()->addMonths(3),
                'budget' => 242000.00,
                'spent' => 0.00,
                'sla_hours' => 48,
            ],
            [
                'contract_number' => 'CT-2026-039',
                'title' => 'University Lab Clean Power',
                'description' => 'Clean power branches and UPS for sensitive laboratories.',
                'client_id' => $users[2]->id,
                'assigned_to' => null,
                'status' => 'approved',
                'priority' => 'high',
                'start_date' => $now->copy()->addWeeks(4),
                'due_date' => $now->copy()->addMonths(6),
                'budget' => 368000.00,
                'spent' => 0.00,
                'sla_hours' => 36,
            ],
            [
                'contract_number' => 'CT-2026-040',
                'title' => 'Retail Refrigeration Telemetry',
                'description' => 'Telemetry and alerting for 48 refrigeration units.',
                'client_id' => $users[0]->id,
                'assigned_to' => $users[1]->id,
                'status' => 'approved',
                'priority' => 'medium',
                'start_date' => $now->copy()->addWeeks(2),
                'due_date' => $now->copy()->addMonths(4),
                'budget' => 124000.00,
                'spent' => 0.00,
                'sla_hours' => 60,
            ],
            [
                'contract_number' => 'CT-2026-041',
                'title' => 'Airport Perimeter Fiber Ring',
                'description' => 'Redundant ring for perimeter surveillance and sensors.',
                'client_id' => $users[2]->id,
                'assigned_to' => null,
                'status' => 'approved',
                'priority' => 'critical',
                'start_date' => $now->copy()->addDays(10),
                'due_date' => $now->copy()->addMonths(5),
                'budget' => 410000.00,
                'spent' => 0.00,
                'sla_hours' => 24,
            ],
            [
                'contract_number' => 'CT-2026-042',
                'title' => 'Port Warehouse Leak Detection',
                'description' => 'Acoustic leak detection on main chilled water branch.',
                'client_id' => $users[1]->id,
                'assigned_to' => $users[0]->id,
                'status' => 'approved',
                'priority' => 'medium',
                'start_date' => $now->copy()->addWeeks(1),
                'due_date' => $now->copy()->addMonths(2),
                'budget' => 89000.00,
                'spent' => 0.00,
                'sla_hours' => 72,
            ],
            [
                'contract_number' => 'CT-2026-043',
                'title' => 'Emergency Dispatch Room Retrofit',
                'description' => 'Acoustic treatment and power redundancy upgrade.',
                'client_id' => $users[0]->id,
                'assigned_to' => null,
                'status' => 'approved',
                'priority' => 'high',
                'start_date' => $now->copy()->addWeeks(3),
                'due_date' => $now->copy()->addMonths(3),
                'budget' => 176000.00,
                'spent' => 0.00,
                'sla_hours' => 48,
            ],

            // DONE +6
            [
                'contract_number' => 'CT-2026-044',
                'title' => 'Municipal Building Lighting Migration',
                'description' => 'Legacy fluorescent to LED migration in admin offices.',
                'client_id' => $users[0]->id,
                'assigned_to' => $users[1]->id,
                'status' => 'done',
                'priority' => 'medium',
                'start_date' => $now->copy()->subMonths(5),
                'due_date' => $now->copy()->subMonths(1),
                'budget' => 97000.00,
                'spent' => 95200.00,
                'completed_at' => $now->copy()->subMonths(1),
                'sla_hours' => 84,
            ],
            [
                'contract_number' => 'CT-2026-045',
                'title' => 'Hospital Pneumatic Tube Monitoring',
                'description' => 'Monitoring and fault alerting for tube dispatch nodes.',
                'client_id' => $users[1]->id,
                'assigned_to' => $users[2]->id,
                'status' => 'done',
                'priority' => 'high',
                'start_date' => $now->copy()->subMonths(4),
                'due_date' => $now->copy()->subWeeks(3),
                'budget' => 143000.00,
                'spent' => 141500.00,
                'completed_at' => $now->copy()->subWeeks(3),
                'sla_hours' => 48,
            ],
            [
                'contract_number' => 'CT-2026-046',
                'title' => 'Campus Core Switch Replacement',
                'description' => 'Core stack replacement and cutover in maintenance window.',
                'client_id' => $users[2]->id,
                'assigned_to' => $users[0]->id,
                'status' => 'done',
                'priority' => 'critical',
                'start_date' => $now->copy()->subMonths(6),
                'due_date' => $now->copy()->subMonths(2),
                'budget' => 289000.00,
                'spent' => 288900.00,
                'completed_at' => $now->copy()->subMonths(2),
                'sla_hours' => 24,
            ],
            [
                'contract_number' => 'CT-2026-047',
                'title' => 'Factory Boiler Safety Interlocks',
                'description' => 'Interlock redesign and validation test campaign.',
                'client_id' => $users[0]->id,
                'assigned_to' => $users[2]->id,
                'status' => 'done',
                'priority' => 'high',
                'start_date' => $now->copy()->subMonths(3),
                'due_date' => $now->copy()->subWeeks(4),
                'budget' => 119000.00,
                'spent' => 118400.00,
                'completed_at' => $now->copy()->subWeeks(4),
                'sla_hours' => 36,
            ],
            [
                'contract_number' => 'CT-2026-048',
                'title' => 'Airport Generator Load Bank Testing',
                'description' => 'Load bank tests and reporting for emergency generators.',
                'client_id' => $users[1]->id,
                'assigned_to' => $users[0]->id,
                'status' => 'done',
                'priority' => 'medium',
                'start_date' => $now->copy()->subMonths(2),
                'due_date' => $now->copy()->subDays(20),
                'budget' => 78000.00,
                'spent' => 77450.00,
                'completed_at' => $now->copy()->subDays(20),
                'sla_hours' => 72,
            ],
            [
                'contract_number' => 'CT-2026-049',
                'title' => 'Retail WAN QoS Standardization',
                'description' => 'QoS template rollout for voice/video over MPLS.',
                'client_id' => $users[2]->id,
                'assigned_to' => $users[1]->id,
                'status' => 'done',
                'priority' => 'medium',
                'start_date' => $now->copy()->subMonths(3),
                'due_date' => $now->copy()->subDays(12),
                'budget' => 101000.00,
                'spent' => 100200.00,
                'completed_at' => $now->copy()->subDays(12),
                'sla_hours' => 60,
            ],

            // BLOCKED +11
            [
                'contract_number' => 'CT-2026-050',
                'title' => 'City Hall Elevator Telemetry',
                'description' => 'Blocked due to delayed permit for shaft cabling.',
                'client_id' => $users[0]->id,
                'assigned_to' => null,
                'status' => 'blocked',
                'priority' => 'medium',
                'start_date' => $now->copy()->subWeeks(2),
                'due_date' => $now->copy()->addMonths(2),
                'budget' => 112000.00,
                'spent' => 15000.00,
                'sla_hours' => 96,
            ],
            [
                'contract_number' => 'CT-2026-051',
                'title' => 'Harbor Thermal Camera Expansion',
                'description' => 'Blocked by customs hold on imported camera modules.',
                'client_id' => $users[1]->id,
                'assigned_to' => $users[2]->id,
                'status' => 'blocked',
                'priority' => 'high',
                'start_date' => $now->copy()->subWeeks(5),
                'due_date' => $now->copy()->addWeeks(8),
                'budget' => 244000.00,
                'spent' => 39200.00,
                'sla_hours' => 48,
            ],
            [
                'contract_number' => 'CT-2026-052',
                'title' => 'Factory Chiller Pipe Re-route',
                'description' => 'Blocked pending structural approval.',
                'client_id' => $users[2]->id,
                'assigned_to' => null,
                'status' => 'blocked',
                'priority' => 'high',
                'start_date' => $now->copy()->subWeeks(3),
                'due_date' => $now->copy()->addMonths(3),
                'budget' => 171000.00,
                'spent' => 26800.00,
                'sla_hours' => 72,
            ],
            [
                'contract_number' => 'CT-2026-053',
                'title' => 'Metro Depot Access Gates',
                'description' => 'Blocked due to stakeholder change request freeze.',
                'client_id' => $users[0]->id,
                'assigned_to' => $users[1]->id,
                'status' => 'blocked',
                'priority' => 'medium',
                'start_date' => $now->copy()->subDays(25),
                'due_date' => $now->copy()->addDays(45),
                'budget' => 133000.00,
                'spent' => 19800.00,
                'sla_hours' => 84,
            ],
            [
                'contract_number' => 'CT-2026-054',
                'title' => 'Hospital OR Airflow Validation',
                'description' => 'Blocked while waiting for external accreditation audit slot.',
                'client_id' => $users[1]->id,
                'assigned_to' => null,
                'status' => 'blocked',
                'priority' => 'critical',
                'start_date' => $now->copy()->subDays(18),
                'due_date' => $now->copy()->addDays(32),
                'budget' => 208000.00,
                'spent' => 41000.00,
                'sla_hours' => 24,
            ],
            [
                'contract_number' => 'CT-2026-055',
                'title' => 'Campus Card Printer Consolidation',
                'description' => 'Blocked due to vendor bankruptcy and replacement tender.',
                'client_id' => $users[2]->id,
                'assigned_to' => $users[0]->id,
                'status' => 'blocked',
                'priority' => 'low',
                'start_date' => $now->copy()->subWeeks(6),
                'due_date' => $now->copy()->addMonths(4),
                'budget' => 68000.00,
                'spent' => 9500.00,
                'sla_hours' => 120,
            ],
            [
                'contract_number' => 'CT-2026-056',
                'title' => 'Airport Baggage Belt Sensors',
                'description' => 'Blocked, waiting for night-shift access authorization.',
                'client_id' => $users[0]->id,
                'assigned_to' => $users[2]->id,
                'status' => 'blocked',
                'priority' => 'medium',
                'start_date' => $now->copy()->subWeeks(4),
                'due_date' => $now->copy()->addWeeks(7),
                'budget' => 126000.00,
                'spent' => 22400.00,
                'sla_hours' => 60,
            ],
            [
                'contract_number' => 'CT-2026-057',
                'title' => 'Port Fire Suppression Upgrade',
                'description' => 'Blocked due to revised fire code interpretation.',
                'client_id' => $users[1]->id,
                'assigned_to' => null,
                'status' => 'blocked',
                'priority' => 'high',
                'start_date' => $now->copy()->subWeeks(7),
                'due_date' => $now->copy()->addMonths(2),
                'budget' => 302000.00,
                'spent' => 58000.00,
                'sla_hours' => 36,
            ],
            [
                'contract_number' => 'CT-2026-058',
                'title' => 'City Surveillance Storage Cluster',
                'description' => 'Blocked due to procurement dispute over storage nodes.',
                'client_id' => $users[2]->id,
                'assigned_to' => $users[1]->id,
                'status' => 'blocked',
                'priority' => 'high',
                'start_date' => $now->copy()->subWeeks(3),
                'due_date' => $now->copy()->addMonths(3),
                'budget' => 358000.00,
                'spent' => 47200.00,
                'sla_hours' => 48,
            ],
            [
                'contract_number' => 'CT-2026-059',
                'title' => 'Industrial Air Compressor Telemetry',
                'description' => 'Blocked due to OT-security approval pending.',
                'client_id' => $users[0]->id,
                'assigned_to' => null,
                'status' => 'blocked',
                'priority' => 'medium',
                'start_date' => $now->copy()->subWeeks(2),
                'due_date' => $now->copy()->addMonths(2),
                'budget' => 93000.00,
                'spent' => 13800.00,
                'sla_hours' => 72,
            ],
            [
                'contract_number' => 'CT-2026-060',
                'title' => 'Emergency Call Center Failover',
                'description' => 'Blocked until telecom provider confirms secondary route readiness.',
                'client_id' => $users[1]->id,
                'assigned_to' => $users[0]->id,
                'status' => 'blocked',
                'priority' => 'critical',
                'start_date' => $now->copy()->subDays(14),
                'due_date' => $now->copy()->addDays(26),
                'budget' => 265000.00,
                'spent' => 62000.00,
                'sla_hours' => 24,
            ],
        ];

        $persistedContracts = collect();

        foreach ($contracts as $contractData) {
            // Randomly assign one of the 5 tenants
            $contractData['tenant_id'] = $tenants->random()->id;

            $persistedContracts->push(
                Contract::updateOrCreate(
                    [
                        'tenant_id' => $contractData['tenant_id'],
                        'contract_number' => $contractData['contract_number'],
                    ],
                    $contractData
                )
            );
        }

        $this->seedContractStatusHistory($persistedContracts, $users[0]);
        $this->seedContractIncidents($persistedContracts, $users);
    }

    private function seedContractStatusHistory(Collection $contracts, User $changedBy): void
    {
        $transitionsByStatus = [
            'approved' => [
                ['draft', 'approved'],
            ],
            'in_progress' => [
                ['draft', 'approved'],
                ['approved', 'in_progress'],
            ],
            'blocked' => [
                ['draft', 'approved'],
                ['approved', 'in_progress'],
                ['in_progress', 'blocked'],
            ],
            'done' => [
                ['draft', 'approved'],
                ['approved', 'in_progress'],
                ['in_progress', 'done'],
            ],
        ];

        foreach ($contracts as $contract) {
            $transitions = $transitionsByStatus[$contract->status] ?? [];

            foreach ($transitions as $index => [$from, $to]) {
                $changedAt = ($contract->created_at ?? now())->copy()->addMinutes($index + 1)->toDateTimeString();

                $reason = match ([$from, $to]) {
                    ['draft', 'approved'] => 'Contract approved by management',
                    ['approved', 'in_progress'] => 'Work started, resources allocated',
                    ['in_progress', 'blocked'] => 'Blocked pending external dependency',
                    ['in_progress', 'done'] => 'Contract completed successfully',
                    default => 'Status updated',
                };

                ContractStatusHistory::updateOrCreate(
                    [
                        'contract_id' => $contract->id,
                        'from_status' => $from,
                        'to_status' => $to,
                        'changed_at' => $changedAt,
                    ],
                    [
                        'old_status' => $from,
                        'new_status' => $to,
                        'changed_by' => $changedBy->id,
                        'reason' => $reason,
                    ]
                );
            }
        }
    }

    private function seedContractIncidents(Collection $contracts, Collection $users): void
    {
        $reporter = $users[0];
        $fallbackAssignee = $users[1] ?? $users[0];

        $contracts
            ->filter(fn ($contract) => in_array($contract->status, ['in_progress', 'blocked', 'done'], true))
            ->take(20)
            ->each(function ($contract) use ($reporter, $fallbackAssignee): void {
                $reportedAt = ($contract->updated_at ?? now())->copy()->subHours(2);
                $severity = match ($contract->priority) {
                    'critical' => 'critical',
                    'high' => 'high',
                    default => 'medium',
                };

                $incidentTitle = match ($severity) {
                    'critical' => 'Critical issue affecting contract delivery',
                    'high' => 'Equipment malfunction impacting timeline',
                    default => 'Minor delay reported by field team',
                };

                $incidentDescription = match ($severity) {
                    'critical' => 'Immediate attention required. Issue blocking critical path activities.',
                    'high' => 'Equipment failure detected during routine inspection. Replacement parts ordered.',
                    default => 'Vendor delivery delayed by 2-3 days. Adjusting work schedule accordingly.',
                };

                ContractIncident::updateOrCreate(
                    [
                        'contract_id' => $contract->id,
                        'title' => $incidentTitle,
                    ],
                    [
                        'description' => $incidentDescription,
                        'severity' => $severity,
                        'status' => $contract->status === 'done' ? 'resolved' : 'open',
                        'reported_by' => $reporter->id,
                        'assigned_to' => $contract->assigned_to ?: $fallbackAssignee->id,
                        'reported_at' => $reportedAt,
                        'resolved_at' => $contract->status === 'done' ? $reportedAt->copy()->addHours(6) : null,
                    ]
                );
            });
    }
}
