<?php

namespace Database\Seeders;

use App\Models\Incident;
use App\Models\IncidentAssignment;
use App\Models\IncidentComment;
use App\Models\IncidentEscalation;
use App\Models\IncidentTimeline;
use App\Models\Tenant;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Collection;

class IncidentSeeder extends Seeder
{
    public function run(): void
    {
        // Get all active tenants (expect 5 from DatabaseSeeder)
        $tenants = Tenant::where('status', 'active')->get();
        if ($tenants->isEmpty()) {
            return;
        }

        // Get first tenant for finding users
        $firstTenant = $tenants->first();

        $manager = User::where('tenant_id', $firstTenant->id)
            ->whereHas('roles', fn ($q) => $q->where('name', 'Manager'))
            ->first();

        $technician = User::where('tenant_id', $firstTenant->id)
            ->whereHas('roles', fn ($q) => $q->where('name', 'Technician'))
            ->first();

        $viewer = User::where('tenant_id', $firstTenant->id)
            ->whereHas('roles', fn ($q) => $q->where('name', 'Viewer'))
            ->first();

        $fallbackUsers = User::where('tenant_id', $firstTenant->id)->take(3)->get();
        if ($fallbackUsers->count() < 3) {
            return;
        }

        $users = collect([
            $manager ?? $fallbackUsers[0],
            $technician ?? $fallbackUsers[1],
            $viewer ?? $fallbackUsers[2],
        ])->values();

        $now = now();

        $incidents = [
            // OPEN (10)
            [
                'incident_number' => 'INC-2026-001',
                'title' => 'HVAC Temperature Drift - West Wing',
                'description' => 'Setpoint mismatch in west-wing fan coil loop. Occupant complaints increasing.',
                'category' => 'hvac',
                'severity' => 'medium',
                'status' => 'open',
                'priority' => 'high',
                'reported_by' => $users[0]->id,
                'assigned_to' => null,
                'reported_at' => $now->copy()->subHours(6),
                'sla_resolution_deadline' => $now->copy()->addHours(18),
                'sla_breached' => false,
                'created_at' => $now->copy()->subHours(6),
                'updated_at' => $now->copy()->subHours(2),
            ],
            [
                'incident_number' => 'INC-2026-002',
                'title' => 'Water Leak Sensor Alarm - Server Corridor',
                'description' => 'Leak rope detector triggered under raised floor corridor B.',
                'category' => 'infrastructure',
                'severity' => 'high',
                'status' => 'open',
                'priority' => 'critical',
                'reported_by' => $users[1]->id,
                'assigned_to' => null,
                'reported_at' => $now->copy()->subHours(10),
                'sla_resolution_deadline' => $now->copy()->addHours(6),
                'sla_breached' => false,
                'created_at' => $now->copy()->subHours(10),
                'updated_at' => $now->copy()->subHours(1),
            ],
            [
                'incident_number' => 'INC-2026-003',
                'title' => 'Door Controller Offline - Loading Bay',
                'description' => 'Access controller intermittently unreachable from central security panel.',
                'category' => 'security',
                'severity' => 'medium',
                'status' => 'open',
                'priority' => 'medium',
                'reported_by' => $users[2]->id,
                'assigned_to' => null,
                'reported_at' => $now->copy()->subHours(14),
                'sla_resolution_deadline' => $now->copy()->addHours(20),
                'sla_breached' => false,
                'created_at' => $now->copy()->subHours(14),
                'updated_at' => $now->copy()->subHours(8),
            ],
            [
                'incident_number' => 'INC-2026-004',
                'title' => 'Low Battery Alert - Cold Storage Sensor',
                'description' => 'Temperature sensor battery near depletion in aisle 14.',
                'category' => 'equipment',
                'severity' => 'low',
                'status' => 'open',
                'priority' => 'low',
                'reported_by' => $users[0]->id,
                'assigned_to' => null,
                'reported_at' => $now->copy()->subHours(16),
                'sla_resolution_deadline' => $now->copy()->addDays(2),
                'sla_breached' => false,
                'created_at' => $now->copy()->subHours(16),
                'updated_at' => $now->copy()->subHours(6),
            ],
            [
                'incident_number' => 'INC-2026-005',
                'title' => 'Generator Weekly Test Failed',
                'description' => 'Generator #2 failed to accept load during scheduled weekly test.',
                'category' => 'power',
                'severity' => 'high',
                'status' => 'open',
                'priority' => 'high',
                'reported_by' => $users[1]->id,
                'assigned_to' => null,
                'reported_at' => $now->copy()->subHours(5),
                'sla_resolution_deadline' => $now->copy()->addHours(15),
                'sla_breached' => false,
                'created_at' => $now->copy()->subHours(5),
                'updated_at' => $now->copy()->subHours(1),
            ],
            [
                'incident_number' => 'INC-2026-006',
                'title' => 'Database Backup Partial Completion',
                'description' => 'Nightly backup completed with missing attachments shard.',
                'category' => 'database',
                'severity' => 'high',
                'status' => 'open',
                'priority' => 'critical',
                'reported_by' => $users[2]->id,
                'assigned_to' => null,
                'reported_at' => $now->copy()->subHours(11),
                'sla_resolution_deadline' => $now->copy()->addHours(7),
                'sla_breached' => false,
                'created_at' => $now->copy()->subHours(11),
                'updated_at' => $now->copy()->subHours(3),
            ],
            [
                'incident_number' => 'INC-2026-007',
                'title' => 'Parking Zone C Lighting Out',
                'description' => 'Nine luminaires dark after rain event.',
                'category' => 'infrastructure',
                'severity' => 'medium',
                'status' => 'open',
                'priority' => 'medium',
                'reported_by' => $users[0]->id,
                'assigned_to' => null,
                'reported_at' => $now->copy()->subHours(9),
                'sla_resolution_deadline' => $now->copy()->addHours(17),
                'sla_breached' => false,
                'created_at' => $now->copy()->subHours(9),
                'updated_at' => $now->copy()->subHours(2),
            ],
            [
                'incident_number' => 'INC-2026-008',
                'title' => 'UPS Alarm - Battery String Imbalance',
                'description' => 'String B showing voltage delta outside tolerance.',
                'category' => 'power',
                'severity' => 'high',
                'status' => 'open',
                'priority' => 'high',
                'reported_by' => $users[1]->id,
                'assigned_to' => null,
                'reported_at' => $now->copy()->subHours(7),
                'sla_resolution_deadline' => $now->copy()->addHours(10),
                'sla_breached' => false,
                'created_at' => $now->copy()->subHours(7),
                'updated_at' => $now->copy()->subHours(2),
            ],
            [
                'incident_number' => 'INC-2026-009',
                'title' => 'Switchport Errors - Core Stack',
                'description' => 'CRC errors spiking on uplink interface Te1/1/5.',
                'category' => 'network',
                'severity' => 'medium',
                'status' => 'open',
                'priority' => 'high',
                'reported_by' => $users[2]->id,
                'assigned_to' => null,
                'reported_at' => $now->copy()->subHours(4),
                'sla_resolution_deadline' => $now->copy()->addHours(12),
                'sla_breached' => false,
                'created_at' => $now->copy()->subHours(4),
                'updated_at' => $now->copy()->subHour(),
            ],
            [
                'incident_number' => 'INC-2026-010',
                'title' => 'Fire Door Hold-Open Magnet Fault',
                'description' => 'Fire door #FD-17 not releasing on alarm simulation.',
                'category' => 'safety',
                'severity' => 'high',
                'status' => 'open',
                'priority' => 'critical',
                'reported_by' => $users[0]->id,
                'assigned_to' => null,
                'reported_at' => $now->copy()->subHours(12),
                'sla_resolution_deadline' => $now->copy()->addHours(4),
                'sla_breached' => false,
                'created_at' => $now->copy()->subHours(12),
                'updated_at' => $now->copy()->subHours(1),
            ],

            // ESCALATED (10)
            [
                'incident_number' => 'INC-2026-011',
                'title' => 'Hospital Core Router Thermal Alert',
                'description' => 'Persistent thermal threshold breaches despite fan swap.',
                'category' => 'network',
                'severity' => 'critical',
                'status' => 'escalated',
                'priority' => 'critical',
                'reported_by' => $users[0]->id,
                'assigned_to' => $users[2]->id,
                'reported_at' => $now->copy()->subHours(8),
                'acknowledged_at' => $now->copy()->subHours(7)->subMinutes(30),
                'started_at' => $now->copy()->subHours(7),
                'sla_resolution_deadline' => $now->copy()->addHours(2),
                'sla_breached' => false,
                'created_at' => $now->copy()->subHours(8),
                'updated_at' => $now->copy()->subHours(1),
            ],
            [
                'incident_number' => 'INC-2026-012',
                'title' => 'Ransomware Signature Match - Endpoint Cluster',
                'description' => 'EDR flagged multiple endpoints; containment initiated.',
                'category' => 'security',
                'severity' => 'critical',
                'status' => 'escalated',
                'priority' => 'critical',
                'reported_by' => $users[1]->id,
                'assigned_to' => $users[0]->id,
                'reported_at' => $now->copy()->subHours(6),
                'acknowledged_at' => $now->copy()->subHours(5)->subMinutes(40),
                'started_at' => $now->copy()->subHours(5)->subMinutes(10),
                'sla_resolution_deadline' => $now->copy()->addMinutes(50),
                'sla_breached' => false,
                'created_at' => $now->copy()->subHours(6),
                'updated_at' => $now->copy()->subHours(1),
            ],
            [
                'incident_number' => 'INC-2026-013',
                'title' => 'Cooling Circuit Pressure Drop',
                'description' => 'Pressure loss in chilled-water branch to Hall B.',
                'category' => 'cooling',
                'severity' => 'high',
                'status' => 'escalated',
                'priority' => 'high',
                'reported_by' => $users[2]->id,
                'assigned_to' => $users[1]->id,
                'reported_at' => $now->copy()->subHours(9),
                'acknowledged_at' => $now->copy()->subHours(8)->subMinutes(20),
                'started_at' => $now->copy()->subHours(8),
                'sla_resolution_deadline' => $now->copy()->addHours(5),
                'sla_breached' => false,
                'created_at' => $now->copy()->subHours(9),
                'updated_at' => $now->copy()->subHours(2),
            ],
            [
                'incident_number' => 'INC-2026-014',
                'title' => 'Payment API Timeout Surge',
                'description' => 'Integration timeouts above 20% for partner requests.',
                'category' => 'infrastructure',
                'severity' => 'critical',
                'status' => 'escalated',
                'priority' => 'critical',
                'reported_by' => $users[0]->id,
                'assigned_to' => $users[1]->id,
                'reported_at' => $now->copy()->subHours(7),
                'acknowledged_at' => $now->copy()->subHours(6)->subMinutes(35),
                'started_at' => $now->copy()->subHours(6),
                'sla_resolution_deadline' => $now->copy()->addMinutes(40),
                'sla_breached' => false,
                'created_at' => $now->copy()->subHours(7),
                'updated_at' => $now->copy()->subMinutes(50),
            ],
            [
                'incident_number' => 'INC-2026-015',
                'title' => 'Emergency Exit Controller Flapping',
                'description' => 'Controller reboot loop affecting emergency corridors.',
                'category' => 'safety',
                'severity' => 'high',
                'status' => 'escalated',
                'priority' => 'high',
                'reported_by' => $users[1]->id,
                'assigned_to' => $users[2]->id,
                'reported_at' => $now->copy()->subHours(5),
                'acknowledged_at' => $now->copy()->subHours(4)->subMinutes(15),
                'started_at' => $now->copy()->subHours(4),
                'sla_resolution_deadline' => $now->copy()->addHours(4),
                'sla_breached' => false,
                'created_at' => $now->copy()->subHours(5),
                'updated_at' => $now->copy()->subHours(1),
            ],
            [
                'incident_number' => 'INC-2026-016',
                'title' => 'Campus Main Switch CPU Spike',
                'description' => 'Sustained CPU utilization > 95% after ACL push.',
                'category' => 'network',
                'severity' => 'high',
                'status' => 'escalated',
                'priority' => 'high',
                'reported_by' => $users[2]->id,
                'assigned_to' => $users[0]->id,
                'reported_at' => $now->copy()->subHours(11),
                'acknowledged_at' => $now->copy()->subHours(10)->subMinutes(50),
                'started_at' => $now->copy()->subHours(10)->subMinutes(20),
                'sla_resolution_deadline' => $now->copy()->addHours(3),
                'sla_breached' => false,
                'created_at' => $now->copy()->subHours(11),
                'updated_at' => $now->copy()->subHours(3),
            ],
            [
                'incident_number' => 'INC-2026-017',
                'title' => 'Smoke Detection False Positive Storm',
                'description' => 'Series of false triggers from detector group D-12.',
                'category' => 'safety',
                'severity' => 'high',
                'status' => 'escalated',
                'priority' => 'high',
                'reported_by' => $users[0]->id,
                'assigned_to' => $users[2]->id,
                'reported_at' => $now->copy()->subHours(13),
                'acknowledged_at' => $now->copy()->subHours(12)->subMinutes(20),
                'started_at' => $now->copy()->subHours(12),
                'sla_resolution_deadline' => $now->copy()->addHours(6),
                'sla_breached' => false,
                'created_at' => $now->copy()->subHours(13),
                'updated_at' => $now->copy()->subHours(4),
            ],
            [
                'incident_number' => 'INC-2026-018',
                'title' => 'Boiler Control PLC Communication Loss',
                'description' => 'Intermittent PLC link to SCADA historian.',
                'category' => 'infrastructure',
                'severity' => 'high',
                'status' => 'escalated',
                'priority' => 'high',
                'reported_by' => $users[1]->id,
                'assigned_to' => $users[0]->id,
                'reported_at' => $now->copy()->subHours(15),
                'acknowledged_at' => $now->copy()->subHours(14)->subMinutes(30),
                'started_at' => $now->copy()->subHours(14),
                'sla_resolution_deadline' => $now->copy()->addHours(7),
                'sla_breached' => false,
                'created_at' => $now->copy()->subHours(15),
                'updated_at' => $now->copy()->subHours(5),
            ],
            [
                'incident_number' => 'INC-2026-019',
                'title' => 'Primary SAN Path Degraded',
                'description' => 'I/O latency spikes after controller failback.',
                'category' => 'database',
                'severity' => 'critical',
                'status' => 'escalated',
                'priority' => 'critical',
                'reported_by' => $users[2]->id,
                'assigned_to' => $users[1]->id,
                'reported_at' => $now->copy()->subHours(4),
                'acknowledged_at' => $now->copy()->subHours(3)->subMinutes(40),
                'started_at' => $now->copy()->subHours(3),
                'sla_resolution_deadline' => $now->copy()->addMinutes(55),
                'sla_breached' => false,
                'created_at' => $now->copy()->subHours(4),
                'updated_at' => $now->copy()->subMinutes(35),
            ],
            [
                'incident_number' => 'INC-2026-020',
                'title' => 'Emergency Phone Trunk Failure',
                'description' => 'Two trunks down in emergency call center.',
                'category' => 'network',
                'severity' => 'critical',
                'status' => 'escalated',
                'priority' => 'critical',
                'reported_by' => $users[0]->id,
                'assigned_to' => $users[2]->id,
                'reported_at' => $now->copy()->subHours(3),
                'acknowledged_at' => $now->copy()->subHours(2)->subMinutes(35),
                'started_at' => $now->copy()->subHours(2),
                'sla_resolution_deadline' => $now->copy()->addMinutes(45),
                'sla_breached' => false,
                'created_at' => $now->copy()->subHours(3),
                'updated_at' => $now->copy()->subMinutes(25),
            ],

            // IN_PROGRESS (10)
            [
                'incident_number' => 'INC-2026-021',
                'title' => 'Chiller Pump Vibration Above Limit',
                'description' => 'Bearing wear suspected; replacement prep in progress.',
                'category' => 'hvac',
                'severity' => 'high',
                'status' => 'in_progress',
                'priority' => 'high',
                'reported_by' => $users[1]->id,
                'assigned_to' => $users[2]->id,
                'reported_at' => $now->copy()->subHours(20),
                'acknowledged_at' => $now->copy()->subHours(19)->subMinutes(30),
                'started_at' => $now->copy()->subHours(18),
                'sla_resolution_deadline' => $now->copy()->addHours(8),
                'sla_breached' => false,
                'created_at' => $now->copy()->subHours(20),
                'updated_at' => $now->copy()->subHours(1),
            ],
            [
                'incident_number' => 'INC-2026-022',
                'title' => 'Switch Firmware Rollback',
                'description' => 'Rollback after unstable release caused packet drops.',
                'category' => 'network',
                'severity' => 'medium',
                'status' => 'in_progress',
                'priority' => 'medium',
                'reported_by' => $users[0]->id,
                'assigned_to' => $users[1]->id,
                'reported_at' => $now->copy()->subHours(12),
                'acknowledged_at' => $now->copy()->subHours(11)->subMinutes(40),
                'started_at' => $now->copy()->subHours(11),
                'sla_resolution_deadline' => $now->copy()->addHours(14),
                'sla_breached' => false,
                'created_at' => $now->copy()->subHours(12),
                'updated_at' => $now->copy()->subMinutes(40),
            ],
            [
                'incident_number' => 'INC-2026-023',
                'title' => 'Panelboard Thermal Hotspot',
                'description' => 'IR scan found hotspot on feeder breaker.',
                'category' => 'power',
                'severity' => 'high',
                'status' => 'in_progress',
                'priority' => 'high',
                'reported_by' => $users[2]->id,
                'assigned_to' => $users[0]->id,
                'reported_at' => $now->copy()->subHours(16),
                'acknowledged_at' => $now->copy()->subHours(15)->subMinutes(35),
                'started_at' => $now->copy()->subHours(15),
                'sla_resolution_deadline' => $now->copy()->addHours(9),
                'sla_breached' => false,
                'created_at' => $now->copy()->subHours(16),
                'updated_at' => $now->copy()->subHours(2),
            ],
            [
                'incident_number' => 'INC-2026-024',
                'title' => 'Patch Window - App Cluster',
                'description' => 'Security patch deployment at 65%, rollback ready.',
                'category' => 'infrastructure',
                'severity' => 'medium',
                'status' => 'in_progress',
                'priority' => 'medium',
                'reported_by' => $users[0]->id,
                'assigned_to' => $users[2]->id,
                'reported_at' => $now->copy()->subHours(9),
                'acknowledged_at' => $now->copy()->subHours(8)->subMinutes(40),
                'started_at' => $now->copy()->subHours(8),
                'sla_resolution_deadline' => $now->copy()->addHours(16),
                'sla_breached' => false,
                'created_at' => $now->copy()->subHours(9),
                'updated_at' => $now->copy()->subHour(),
            ],
            [
                'incident_number' => 'INC-2026-025',
                'title' => 'CCTV NVR Storage Cleanup',
                'description' => 'Retention exceeded; tiering policy tuning underway.',
                'category' => 'security',
                'severity' => 'low',
                'status' => 'in_progress',
                'priority' => 'low',
                'reported_by' => $users[1]->id,
                'assigned_to' => $users[0]->id,
                'reported_at' => $now->copy()->subDays(1),
                'acknowledged_at' => $now->copy()->subDays(1)->addMinutes(40),
                'started_at' => $now->copy()->subDays(1)->addHours(2),
                'sla_resolution_deadline' => $now->copy()->addDays(2),
                'sla_breached' => false,
                'created_at' => $now->copy()->subDays(1),
                'updated_at' => $now->copy()->subHours(5),
            ],
            [
                'incident_number' => 'INC-2026-026',
                'title' => 'Fire Alarm Zone Mapping Correction',
                'description' => 'Wrong panel-to-zone labels being corrected live.',
                'category' => 'safety',
                'severity' => 'medium',
                'status' => 'in_progress',
                'priority' => 'medium',
                'reported_by' => $users[2]->id,
                'assigned_to' => $users[1]->id,
                'reported_at' => $now->copy()->subHours(18),
                'acknowledged_at' => $now->copy()->subHours(17)->subMinutes(15),
                'started_at' => $now->copy()->subHours(17),
                'sla_resolution_deadline' => $now->copy()->addHours(20),
                'sla_breached' => false,
                'created_at' => $now->copy()->subHours(18),
                'updated_at' => $now->copy()->subHours(3),
            ],
            [
                'incident_number' => 'INC-2026-027',
                'title' => 'DB Replica Catch-up Lag',
                'description' => 'Replica lag at 19 minutes during ETL window.',
                'category' => 'database',
                'severity' => 'high',
                'status' => 'in_progress',
                'priority' => 'high',
                'reported_by' => $users[0]->id,
                'assigned_to' => $users[2]->id,
                'reported_at' => $now->copy()->subHours(13),
                'acknowledged_at' => $now->copy()->subHours(12)->subMinutes(45),
                'started_at' => $now->copy()->subHours(12),
                'sla_resolution_deadline' => $now->copy()->addHours(11),
                'sla_breached' => false,
                'created_at' => $now->copy()->subHours(13),
                'updated_at' => $now->copy()->subHours(2),
            ],
            [
                'incident_number' => 'INC-2026-028',
                'title' => 'Access Badge Sync Delay',
                'description' => 'HR -> ACS sync job delayed for new users.',
                'category' => 'security',
                'severity' => 'medium',
                'status' => 'in_progress',
                'priority' => 'medium',
                'reported_by' => $users[1]->id,
                'assigned_to' => $users[0]->id,
                'reported_at' => $now->copy()->subHours(22),
                'acknowledged_at' => $now->copy()->subHours(21)->subMinutes(15),
                'started_at' => $now->copy()->subHours(20),
                'sla_resolution_deadline' => $now->copy()->addHours(15),
                'sla_breached' => false,
                'created_at' => $now->copy()->subHours(22),
                'updated_at' => $now->copy()->subHours(6),
            ],
            [
                'incident_number' => 'INC-2026-029',
                'title' => 'AHU Filter Differential Pressure High',
                'description' => 'Filter bank replacement in progress across zones A-C.',
                'category' => 'hvac',
                'severity' => 'medium',
                'status' => 'in_progress',
                'priority' => 'high',
                'reported_by' => $users[2]->id,
                'assigned_to' => $users[1]->id,
                'reported_at' => $now->copy()->subHours(15),
                'acknowledged_at' => $now->copy()->subHours(14)->subMinutes(20),
                'started_at' => $now->copy()->subHours(14),
                'sla_resolution_deadline' => $now->copy()->addHours(12),
                'sla_breached' => false,
                'created_at' => $now->copy()->subHours(15),
                'updated_at' => $now->copy()->subHours(2),
            ],
            [
                'incident_number' => 'INC-2026-030',
                'title' => 'Video Wall Display Controller Replacement',
                'description' => 'Controller card replacement underway in command room.',
                'category' => 'equipment',
                'severity' => 'medium',
                'status' => 'in_progress',
                'priority' => 'medium',
                'reported_by' => $users[0]->id,
                'assigned_to' => $users[2]->id,
                'reported_at' => $now->copy()->subHours(17),
                'acknowledged_at' => $now->copy()->subHours(16)->subMinutes(45),
                'started_at' => $now->copy()->subHours(16),
                'sla_resolution_deadline' => $now->copy()->addHours(18),
                'sla_breached' => false,
                'created_at' => $now->copy()->subHours(17),
                'updated_at' => $now->copy()->subHours(4),
            ],

            // RESOLVED (10)
            [
                'incident_number' => 'INC-2026-031',
                'title' => 'Retail VPN Disconnects',
                'description' => 'Resolved by tunnel MTU correction and keepalive tuning.',
                'category' => 'network',
                'severity' => 'medium',
                'status' => 'resolved',
                'priority' => 'medium',
                'reported_by' => $users[1]->id,
                'assigned_to' => $users[2]->id,
                'reported_at' => $now->copy()->subDays(2),
                'acknowledged_at' => $now->copy()->subDays(2)->addMinutes(30),
                'started_at' => $now->copy()->subDays(2)->addHours(1),
                'resolved_at' => $now->copy()->subDays(1)->addHours(6),
                'sla_resolution_deadline' => $now->copy()->subDays(1)->addHours(9),
                'sla_breached' => false,
                'created_at' => $now->copy()->subDays(2),
                'updated_at' => $now->copy()->subDays(1)->addHours(6),
            ],
            [
                'incident_number' => 'INC-2026-032',
                'title' => 'Data Hall Humidity Spike',
                'description' => 'Resolved after humidifier valve recalibration.',
                'category' => 'cooling',
                'severity' => 'high',
                'status' => 'resolved',
                'priority' => 'high',
                'reported_by' => $users[2]->id,
                'assigned_to' => $users[0]->id,
                'reported_at' => $now->copy()->subDays(3),
                'acknowledged_at' => $now->copy()->subDays(3)->addMinutes(20),
                'started_at' => $now->copy()->subDays(3)->addHours(1),
                'resolved_at' => $now->copy()->subDays(2)->addHours(5),
                'sla_resolution_deadline' => $now->copy()->subDays(2)->addHours(8),
                'sla_breached' => false,
                'created_at' => $now->copy()->subDays(3),
                'updated_at' => $now->copy()->subDays(2)->addHours(5),
            ],
            [
                'incident_number' => 'INC-2026-033',
                'title' => 'Generator Coolant Low',
                'description' => 'Coolant replenished, no leak detected in follow-up test.',
                'category' => 'power',
                'severity' => 'medium',
                'status' => 'resolved',
                'priority' => 'medium',
                'reported_by' => $users[0]->id,
                'assigned_to' => $users[1]->id,
                'reported_at' => $now->copy()->subDays(4),
                'acknowledged_at' => $now->copy()->subDays(4)->addMinutes(25),
                'started_at' => $now->copy()->subDays(4)->addHours(1),
                'resolved_at' => $now->copy()->subDays(3)->addHours(3),
                'sla_resolution_deadline' => $now->copy()->subDays(3)->addHours(5),
                'sla_breached' => false,
                'created_at' => $now->copy()->subDays(4),
                'updated_at' => $now->copy()->subDays(3)->addHours(3),
            ],
            [
                'incident_number' => 'INC-2026-034',
                'title' => 'Badge Printer Driver Crash',
                'description' => 'Resolved by vendor hotfix and print queue reset.',
                'category' => 'equipment',
                'severity' => 'low',
                'status' => 'resolved',
                'priority' => 'low',
                'reported_by' => $users[1]->id,
                'assigned_to' => $users[0]->id,
                'reported_at' => $now->copy()->subDays(1),
                'acknowledged_at' => $now->copy()->subDays(1)->addMinutes(10),
                'started_at' => $now->copy()->subDays(1)->addMinutes(35),
                'resolved_at' => $now->copy()->subHours(16),
                'sla_resolution_deadline' => $now->copy()->subHours(10),
                'sla_breached' => false,
                'created_at' => $now->copy()->subDays(1),
                'updated_at' => $now->copy()->subHours(16),
            ],
            [
                'incident_number' => 'INC-2026-035',
                'title' => 'Firewall Rule Regression',
                'description' => 'Rollback + corrected policy push completed.',
                'category' => 'security',
                'severity' => 'high',
                'status' => 'resolved',
                'priority' => 'high',
                'reported_by' => $users[2]->id,
                'assigned_to' => $users[1]->id,
                'reported_at' => $now->copy()->subDays(5),
                'acknowledged_at' => $now->copy()->subDays(5)->addMinutes(15),
                'started_at' => $now->copy()->subDays(5)->addMinutes(40),
                'resolved_at' => $now->copy()->subDays(4)->addHours(7),
                'sla_resolution_deadline' => $now->copy()->subDays(4)->addHours(9),
                'sla_breached' => false,
                'created_at' => $now->copy()->subDays(5),
                'updated_at' => $now->copy()->subDays(4)->addHours(7),
            ],
            [
                'incident_number' => 'INC-2026-036',
                'title' => 'Boiler Loop Pressure Alarm',
                'description' => 'Expansion vessel replaced and pressure stabilized.',
                'category' => 'hvac',
                'severity' => 'medium',
                'status' => 'resolved',
                'priority' => 'medium',
                'reported_by' => $users[0]->id,
                'assigned_to' => $users[2]->id,
                'reported_at' => $now->copy()->subDays(6),
                'acknowledged_at' => $now->copy()->subDays(6)->addMinutes(35),
                'started_at' => $now->copy()->subDays(6)->addHours(1),
                'resolved_at' => $now->copy()->subDays(5)->addHours(2),
                'sla_resolution_deadline' => $now->copy()->subDays(5)->addHours(4),
                'sla_breached' => false,
                'created_at' => $now->copy()->subDays(6),
                'updated_at' => $now->copy()->subDays(5)->addHours(2),
            ],
            [
                'incident_number' => 'INC-2026-037',
                'title' => 'Storage Array Cache Warning',
                'description' => 'Cache battery module replaced and cache re-enabled.',
                'category' => 'database',
                'severity' => 'high',
                'status' => 'resolved',
                'priority' => 'high',
                'reported_by' => $users[2]->id,
                'assigned_to' => $users[1]->id,
                'reported_at' => $now->copy()->subDays(3),
                'acknowledged_at' => $now->copy()->subDays(3)->addMinutes(12),
                'started_at' => $now->copy()->subDays(3)->addMinutes(40),
                'resolved_at' => $now->copy()->subDays(2)->addHours(9),
                'sla_resolution_deadline' => $now->copy()->subDays(2)->addHours(11),
                'sla_breached' => false,
                'created_at' => $now->copy()->subDays(3),
                'updated_at' => $now->copy()->subDays(2)->addHours(9),
            ],
            [
                'incident_number' => 'INC-2026-038',
                'title' => 'Emergency Exit Sign Circuit Fault',
                'description' => 'Faulty driver replaced; circuit passed test.',
                'category' => 'safety',
                'severity' => 'medium',
                'status' => 'resolved',
                'priority' => 'medium',
                'reported_by' => $users[1]->id,
                'assigned_to' => $users[0]->id,
                'reported_at' => $now->copy()->subDays(2)->subHours(6),
                'acknowledged_at' => $now->copy()->subDays(2)->subHours(5)->addMinutes(20),
                'started_at' => $now->copy()->subDays(2)->subHours(4),
                'resolved_at' => $now->copy()->subDays(1)->subHours(20),
                'sla_resolution_deadline' => $now->copy()->subDays(1)->subHours(18),
                'sla_breached' => false,
                'created_at' => $now->copy()->subDays(2)->subHours(6),
                'updated_at' => $now->copy()->subDays(1)->subHours(20),
            ],
            [
                'incident_number' => 'INC-2026-039',
                'title' => 'CRAC Condensate Pump Stall',
                'description' => 'Pump replaced during maintenance window.',
                'category' => 'cooling',
                'severity' => 'high',
                'status' => 'resolved',
                'priority' => 'high',
                'reported_by' => $users[0]->id,
                'assigned_to' => $users[2]->id,
                'reported_at' => $now->copy()->subDays(7),
                'acknowledged_at' => $now->copy()->subDays(7)->addMinutes(18),
                'started_at' => $now->copy()->subDays(7)->addHours(1),
                'resolved_at' => $now->copy()->subDays(6)->addHours(6),
                'sla_resolution_deadline' => $now->copy()->subDays(6)->addHours(8),
                'sla_breached' => false,
                'created_at' => $now->copy()->subDays(7),
                'updated_at' => $now->copy()->subDays(6)->addHours(6),
            ],
            [
                'incident_number' => 'INC-2026-040',
                'title' => 'DHCP Scope Exhaustion',
                'description' => 'Scope expanded and stale leases reclaimed.',
                'category' => 'network',
                'severity' => 'medium',
                'status' => 'resolved',
                'priority' => 'medium',
                'reported_by' => $users[2]->id,
                'assigned_to' => $users[1]->id,
                'reported_at' => $now->copy()->subDays(2),
                'acknowledged_at' => $now->copy()->subDays(2)->addMinutes(8),
                'started_at' => $now->copy()->subDays(2)->addMinutes(30),
                'resolved_at' => $now->copy()->subDays(1)->addHours(2),
                'sla_resolution_deadline' => $now->copy()->subDays(1)->addHours(4),
                'sla_breached' => false,
                'created_at' => $now->copy()->subDays(2),
                'updated_at' => $now->copy()->subDays(1)->addHours(2),
            ],

            // SLA BREACHED (10) -> valid status + sla_breached=true
            [
                'incident_number' => 'INC-2026-041',
                'title' => 'Main Website Outage',
                'description' => 'Frontend unreachable due to upstream LB issue. SLA exceeded.',
                'category' => 'infrastructure',
                'severity' => 'critical',
                'status' => 'escalated',
                'priority' => 'critical',
                'reported_by' => $users[0]->id,
                'assigned_to' => $users[1]->id,
                'reported_at' => $now->copy()->subHours(14),
                'acknowledged_at' => $now->copy()->subHours(13)->subMinutes(20),
                'started_at' => $now->copy()->subHours(13),
                'sla_resolution_deadline' => $now->copy()->subHours(4),
                'sla_breached' => true,
                'created_at' => $now->copy()->subHours(14),
                'updated_at' => $now->copy()->subHours(1),
            ],
            [
                'incident_number' => 'INC-2026-042',
                'title' => 'API Latency > SLA',
                'description' => 'Sustained p95 latency above contractual threshold.',
                'category' => 'infrastructure',
                'severity' => 'critical',
                'status' => 'in_progress',
                'priority' => 'critical',
                'reported_by' => $users[1]->id,
                'assigned_to' => $users[2]->id,
                'reported_at' => $now->copy()->subHours(12),
                'acknowledged_at' => $now->copy()->subHours(11)->subMinutes(50),
                'started_at' => $now->copy()->subHours(11),
                'sla_resolution_deadline' => $now->copy()->subHours(3),
                'sla_breached' => true,
                'created_at' => $now->copy()->subHours(12),
                'updated_at' => $now->copy()->subHours(2),
            ],
            [
                'incident_number' => 'INC-2026-043',
                'title' => 'Critical CCTV Recording Gap',
                'description' => 'Recording service stalled; retention gap confirmed.',
                'category' => 'security',
                'severity' => 'critical',
                'status' => 'escalated',
                'priority' => 'critical',
                'reported_by' => $users[2]->id,
                'assigned_to' => $users[0]->id,
                'reported_at' => $now->copy()->subHours(18),
                'acknowledged_at' => $now->copy()->subHours(17)->subMinutes(20),
                'started_at' => $now->copy()->subHours(16),
                'sla_resolution_deadline' => $now->copy()->subHours(8),
                'sla_breached' => true,
                'created_at' => $now->copy()->subHours(18),
                'updated_at' => $now->copy()->subHours(4),
            ],
            [
                'incident_number' => 'INC-2026-044',
                'title' => 'Database Failover Delay',
                'description' => 'Failover exceeded max recovery objective time.',
                'category' => 'database',
                'severity' => 'critical',
                'status' => 'in_progress',
                'priority' => 'critical',
                'reported_by' => $users[0]->id,
                'assigned_to' => $users[2]->id,
                'reported_at' => $now->copy()->subHours(20),
                'acknowledged_at' => $now->copy()->subHours(19)->subMinutes(40),
                'started_at' => $now->copy()->subHours(19),
                'sla_resolution_deadline' => $now->copy()->subHours(10),
                'sla_breached' => true,
                'created_at' => $now->copy()->subHours(20),
                'updated_at' => $now->copy()->subHours(5),
            ],
            [
                'incident_number' => 'INC-2026-045',
                'title' => 'Emergency Generator Auto-Start Failure',
                'description' => 'Auto-start did not trigger during transfer test.',
                'category' => 'power',
                'severity' => 'critical',
                'status' => 'escalated',
                'priority' => 'critical',
                'reported_by' => $users[1]->id,
                'assigned_to' => $users[0]->id,
                'reported_at' => $now->copy()->subHours(16),
                'acknowledged_at' => $now->copy()->subHours(15)->subMinutes(25),
                'started_at' => $now->copy()->subHours(15),
                'sla_resolution_deadline' => $now->copy()->subHours(6),
                'sla_breached' => true,
                'created_at' => $now->copy()->subHours(16),
                'updated_at' => $now->copy()->subHours(3),
            ],
            [
                'incident_number' => 'INC-2026-046',
                'title' => 'Core Firewall Session Exhaustion',
                'description' => 'Session table saturation repeatedly dropping traffic.',
                'category' => 'network',
                'severity' => 'critical',
                'status' => 'in_progress',
                'priority' => 'critical',
                'reported_by' => $users[2]->id,
                'assigned_to' => $users[1]->id,
                'reported_at' => $now->copy()->subHours(22),
                'acknowledged_at' => $now->copy()->subHours(21)->subMinutes(30),
                'started_at' => $now->copy()->subHours(21),
                'sla_resolution_deadline' => $now->copy()->subHours(12),
                'sla_breached' => true,
                'created_at' => $now->copy()->subHours(22),
                'updated_at' => $now->copy()->subHours(6),
            ],
            [
                'incident_number' => 'INC-2026-047',
                'title' => 'Cold Room Compressor Shutdown',
                'description' => 'Compressor trip unresolved beyond contractual response time.',
                'category' => 'hvac',
                'severity' => 'critical',
                'status' => 'open',
                'priority' => 'critical',
                'reported_by' => $users[0]->id,
                'assigned_to' => $users[2]->id,
                'reported_at' => $now->copy()->subHours(24),
                'acknowledged_at' => $now->copy()->subHours(23)->subMinutes(20),
                'started_at' => $now->copy()->subHours(22),
                'sla_resolution_deadline' => $now->copy()->subHours(14),
                'sla_breached' => true,
                'created_at' => $now->copy()->subHours(24),
                'updated_at' => $now->copy()->subHours(8),
            ],
            [
                'incident_number' => 'INC-2026-048',
                'title' => 'Fire Panel Loop Fault - Zone C',
                'description' => 'Loop integrity fault pending replacement modules.',
                'category' => 'safety',
                'severity' => 'critical',
                'status' => 'escalated',
                'priority' => 'critical',
                'reported_by' => $users[1]->id,
                'assigned_to' => $users[0]->id,
                'reported_at' => $now->copy()->subHours(19),
                'acknowledged_at' => $now->copy()->subHours(18)->subMinutes(40),
                'started_at' => $now->copy()->subHours(18),
                'sla_resolution_deadline' => $now->copy()->subHours(9),
                'sla_breached' => true,
                'created_at' => $now->copy()->subHours(19),
                'updated_at' => $now->copy()->subHours(5),
            ],
            [
                'incident_number' => 'INC-2026-049',
                'title' => 'NVR Cluster Metadata Corruption',
                'description' => 'Metadata index corruption delaying evidence retrieval.',
                'category' => 'security',
                'severity' => 'critical',
                'status' => 'in_progress',
                'priority' => 'critical',
                'reported_by' => $users[2]->id,
                'assigned_to' => $users[1]->id,
                'reported_at' => $now->copy()->subHours(21),
                'acknowledged_at' => $now->copy()->subHours(20)->subMinutes(30),
                'started_at' => $now->copy()->subHours(20),
                'sla_resolution_deadline' => $now->copy()->subHours(11),
                'sla_breached' => true,
                'created_at' => $now->copy()->subHours(21),
                'updated_at' => $now->copy()->subHours(7),
            ],
            [
                'incident_number' => 'INC-2026-050',
                'title' => 'Storage Replication Halt',
                'description' => 'Replication stream halted during firmware incompatibility.',
                'category' => 'database',
                'severity' => 'critical',
                'status' => 'open',
                'priority' => 'critical',
                'reported_by' => $users[0]->id,
                'assigned_to' => $users[2]->id,
                'reported_at' => $now->copy()->subHours(26),
                'acknowledged_at' => $now->copy()->subHours(25)->subMinutes(35),
                'started_at' => $now->copy()->subHours(24),
                'sla_resolution_deadline' => $now->copy()->subHours(16),
                'sla_breached' => true,
                'created_at' => $now->copy()->subHours(26),
                'updated_at' => $now->copy()->subHours(9),
            ],
        ];

        $persistedIncidents = collect();

        foreach ($incidents as $incidentData) {
            // Randomly assign one of the 5 tenants
            $incidentData['tenant_id'] = $tenants->random()->id;

            $persistedIncidents->push(
                Incident::updateOrCreate(
                    [
                        'tenant_id' => $incidentData['tenant_id'],
                        'incident_number' => $incidentData['incident_number'],
                    ],
                    $incidentData
                )
            );
        }

        $this->seedIncidentRelations($persistedIncidents, $users);
    }

    private function seedIncidentRelations(Collection $incidents, Collection $users): void
    {
        $fallbackActor = $users[0];

        foreach ($incidents as $incident) {
            $createdAt = ($incident->created_at ?? now())->copy();
            $reporterId = $incident->reported_by ?: $fallbackActor->id;

            IncidentTimeline::updateOrCreate(
                [
                    'incident_id' => $incident->id,
                    'event_type' => 'created',
                    'occurred_at' => $createdAt->toDateTimeString(),
                ],
                [
                    'user_id' => $reporterId,
                    'message' => 'Incident created',
                    'metadata' => ['status' => $incident->status],
                ]
            );

            if ($incident->assigned_to) {
                $assignedAt = ($incident->acknowledged_at ?? $createdAt->copy()->addMinutes(10))->copy();

                IncidentAssignment::updateOrCreate(
                    [
                        'incident_id' => $incident->id,
                        'user_id' => $incident->assigned_to,
                        'role' => 'primary',
                    ],
                    [
                        'assigned_by' => $reporterId,
                        'assignment_reason' => 'Assigned to on-call technician for immediate response',
                        'assigned_at' => $assignedAt,
                        'unassigned_at' => null,
                    ]
                );

                IncidentTimeline::updateOrCreate(
                    [
                        'incident_id' => $incident->id,
                        'event_type' => 'assigned',
                        'occurred_at' => $assignedAt->toDateTimeString(),
                    ],
                    [
                        'user_id' => $reporterId,
                        'message' => 'Incident assigned',
                        'metadata' => [
                            'assigned_to' => $incident->assigned_to,
                            'role' => 'primary',
                        ],
                    ]
                );
            }

            if ($incident->status === 'escalated' && $incident->assigned_to) {
                $escalatedAt = ($incident->started_at ?? $createdAt->copy()->addMinutes(30))->copy();

                IncidentEscalation::updateOrCreate(
                    [
                        'incident_id' => $incident->id,
                        'escalated_to' => $incident->assigned_to,
                        'escalation_level' => 'level_2',
                    ],
                    [
                        'escalated_by' => $reporterId,
                        'reason' => 'Escalated due to complexity and potential impact on critical systems',
                        'notes' => 'Senior engineer required for root cause analysis and resolution strategy',
                        'escalated_at' => $escalatedAt,
                        'resolved_at' => null,
                    ]
                );

                IncidentTimeline::updateOrCreate(
                    [
                        'incident_id' => $incident->id,
                        'event_type' => 'escalated',
                        'occurred_at' => $escalatedAt->toDateTimeString(),
                    ],
                    [
                        'user_id' => $reporterId,
                        'message' => 'Incident escalated',
                        'metadata' => [
                            'escalated_to' => $incident->assigned_to,
                            'escalation_level' => 'level_2',
                        ],
                    ]
                );
            }

            if (in_array($incident->status, ['resolved', 'closed'], true)) {
                $statusAt = ($incident->closed_at ?? $incident->resolved_at ?? $incident->updated_at ?? now())->copy();

                IncidentTimeline::updateOrCreate(
                    [
                        'incident_id' => $incident->id,
                        'event_type' => 'status_changed',
                        'occurred_at' => $statusAt->toDateTimeString(),
                    ],
                    [
                        'user_id' => $reporterId,
                        'message' => 'Incident '.($incident->status === 'closed' ? 'closed' : 'resolved'),
                        'metadata' => ['status' => $incident->status],
                    ]
                );
            }

            if ($incident->id % 3 === 0) {
                $commentedAt = $createdAt->copy()->addHour();

                $comments = [
                    'Initial diagnostics completed. Awaiting vendor response on hardware replacement timeline.',
                    'Root cause identified: firmware incompatibility. Preparing rollback procedure.',
                    'On-site inspection scheduled for tomorrow morning. Coordinating with facility manager.',
                    'Temporary workaround implemented. Monitoring stability before permanent fix.',
                    'Escalating to senior team due to potential impact on SLA commitments.',
                ];

                IncidentComment::updateOrCreate(
                    [
                        'incident_id' => $incident->id,
                        'user_id' => $reporterId,
                        'commented_at' => $commentedAt->toDateTimeString(),
                    ],
                    [
                        'comment' => $comments[$incident->id % count($comments)],
                        'is_internal' => true,
                        'attachments' => null,
                    ]
                );

                IncidentTimeline::updateOrCreate(
                    [
                        'incident_id' => $incident->id,
                        'event_type' => 'note_added',
                        'occurred_at' => $commentedAt->toDateTimeString(),
                    ],
                    [
                        'user_id' => $reporterId,
                        'message' => 'Internal note added',
                        'metadata' => ['is_internal' => true],
                    ]
                );
            }
        }
    }
}
